name: SquadronDirector
main: io.github.cccm5.SquadronDirectorMain
version: ${project.version}
api-version: 1.14
depend: [Movecraft]
commands:
    squadronrelease:
        description: Release the squadron being commanded
        permission: SquadronDirector.release
permissions:
    Squadron.release:
        description: Allows users to release their squadron

