name: SquadronDirector
main: io.github.cccm5.SquadronDirectorMain
version: ${project.version}
api-version: 1.14
depend: [Movecraft]
commands:
    squadronrelease:
        description: Release the squadron being commanded
        permission: SquadronDirector.release
permissions:
    Cargo.load:
        description: Allows users to load cargo
    Cargo.unload:
        description: Allows users unload cargo
    Cargo.cargo:
        description: Allows users to use /cargo
